### ISSUE TITLE
NGNIX Autostart AAPanel

### ISSUE THREAD

**Issue by Giorgi1997** [aaPanel/aaPanel#191]
Hello, I have issue with NGNIX service is not starting automatically after reboot ( , but it is starting normally using web interface when i click Start , `maybe there is some terminal command bt .... to start nginix `? 

maybe is there way to fix it ?

**Comment by aaPanel** [comment]
Hello, we have fixed this issue on the latest version. Please upgrade your panel and re-check again.

**Comment by broogly** [comment]
Hello,
In case your issue is still not fixed you can use this script :
[https://github.com/broogly/aaPanel-nginx-fix.git](https://github.com/broogly/aaPanel-nginx-fix.git)
Hope it helps
